language: node_js
node_js:
  - '0.10'
  - '0.12'
  - 4
  - 5

notifications:
  slack:
    secure: "VXtqyYnQND3q2BAr+qukZP0lhHel5NW+ckn/WoF2XJWmfkA0xH/+WpQwybo06pKzAMhQn8kqP1V1FSEkxhbun7uqcmKS1vqNfonIptyWjzUr45PXKMMwgIXr/ngYN04jjpPzdCzA5qt8DYrSIxHYr92oLMoNJuXKMKTepQUbaQE="

before_install:
  - npm config set strict-ssl false

sudo: false
